### ISSUE TITLE
Button um zu Amberg zu kommen

### ISSUE THREAD

**Issue by JPsychotic** [ReVoluti0n/APPPROG16#16]
Falls man außerhalb Ambergs ist & aber Amberg angucken will, wegen Parkhäusern

**Comment by SPoelloth** [comment]
evtl map nicht verschiebbar machen und nur die übersicht, zentriert auf amberg, anzeigen. falls man in der nähe eines parkhauses ist dann dort hin zoomen mit festem faktor und nicht die positon tracken.
